/**
 * generated by Xtext 2.25.0
 */
package it.polimi.hri_designtime.hriDsl.impl;

import it.polimi.hri_designtime.hriDsl.Coordinates;
import it.polimi.hri_designtime.hriDsl.Fatigue_profile;
import it.polimi.hri_designtime.hriDsl.Free_will_profile;
import it.polimi.hri_designtime.hriDsl.HriDslPackage;
import it.polimi.hri_designtime.hriDsl.Human;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Human</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.impl.HumanImpl#getName <em>Name</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.impl.HumanImpl#getCoordinates <em>Coordinates</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.impl.HumanImpl#getSpeed <em>Speed</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.impl.HumanImpl#getDext <em>Dext</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.impl.HumanImpl#getFatigue_profile <em>Fatigue profile</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.impl.HumanImpl#getFree_will_profile <em>Free will profile</em>}</li>
 * </ul>
 *
 * @generated
 */
public class HumanImpl extends MinimalEObjectImpl.Container implements Human
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getCoordinates() <em>Coordinates</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCoordinates()
   * @generated
   * @ordered
   */
  protected Coordinates coordinates;

  /**
   * The default value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected static final float SPEED_EDEFAULT = 0.0F;

  /**
   * The cached value of the '{@link #getSpeed() <em>Speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpeed()
   * @generated
   * @ordered
   */
  protected float speed = SPEED_EDEFAULT;

  /**
   * The default value of the '{@link #getDext() <em>Dext</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDext()
   * @generated
   * @ordered
   */
  protected static final int DEXT_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDext() <em>Dext</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDext()
   * @generated
   * @ordered
   */
  protected int dext = DEXT_EDEFAULT;

  /**
   * The default value of the '{@link #getFatigue_profile() <em>Fatigue profile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFatigue_profile()
   * @generated
   * @ordered
   */
  protected static final Fatigue_profile FATIGUE_PROFILE_EDEFAULT = Fatigue_profile.YOUNG_HEALTHY;

  /**
   * The cached value of the '{@link #getFatigue_profile() <em>Fatigue profile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFatigue_profile()
   * @generated
   * @ordered
   */
  protected Fatigue_profile fatigue_profile = FATIGUE_PROFILE_EDEFAULT;

  /**
   * The default value of the '{@link #getFree_will_profile() <em>Free will profile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFree_will_profile()
   * @generated
   * @ordered
   */
  protected static final Free_will_profile FREE_WILL_PROFILE_EDEFAULT = Free_will_profile.NORMAL;

  /**
   * The cached value of the '{@link #getFree_will_profile() <em>Free will profile</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFree_will_profile()
   * @generated
   * @ordered
   */
  protected Free_will_profile free_will_profile = FREE_WILL_PROFILE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HumanImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HriDslPackage.Literals.HUMAN;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HriDslPackage.HUMAN__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Coordinates getCoordinates()
  {
    return coordinates;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCoordinates(Coordinates newCoordinates, NotificationChain msgs)
  {
    Coordinates oldCoordinates = coordinates;
    coordinates = newCoordinates;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HriDslPackage.HUMAN__COORDINATES, oldCoordinates, newCoordinates);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCoordinates(Coordinates newCoordinates)
  {
    if (newCoordinates != coordinates)
    {
      NotificationChain msgs = null;
      if (coordinates != null)
        msgs = ((InternalEObject)coordinates).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HriDslPackage.HUMAN__COORDINATES, null, msgs);
      if (newCoordinates != null)
        msgs = ((InternalEObject)newCoordinates).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HriDslPackage.HUMAN__COORDINATES, null, msgs);
      msgs = basicSetCoordinates(newCoordinates, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HriDslPackage.HUMAN__COORDINATES, newCoordinates, newCoordinates));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public float getSpeed()
  {
    return speed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpeed(float newSpeed)
  {
    float oldSpeed = speed;
    speed = newSpeed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HriDslPackage.HUMAN__SPEED, oldSpeed, speed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getDext()
  {
    return dext;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDext(int newDext)
  {
    int oldDext = dext;
    dext = newDext;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HriDslPackage.HUMAN__DEXT, oldDext, dext));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Fatigue_profile getFatigue_profile()
  {
    return fatigue_profile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFatigue_profile(Fatigue_profile newFatigue_profile)
  {
    Fatigue_profile oldFatigue_profile = fatigue_profile;
    fatigue_profile = newFatigue_profile == null ? FATIGUE_PROFILE_EDEFAULT : newFatigue_profile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HriDslPackage.HUMAN__FATIGUE_PROFILE, oldFatigue_profile, fatigue_profile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Free_will_profile getFree_will_profile()
  {
    return free_will_profile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFree_will_profile(Free_will_profile newFree_will_profile)
  {
    Free_will_profile oldFree_will_profile = free_will_profile;
    free_will_profile = newFree_will_profile == null ? FREE_WILL_PROFILE_EDEFAULT : newFree_will_profile;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HriDslPackage.HUMAN__FREE_WILL_PROFILE, oldFree_will_profile, free_will_profile));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HriDslPackage.HUMAN__COORDINATES:
        return basicSetCoordinates(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HriDslPackage.HUMAN__NAME:
        return getName();
      case HriDslPackage.HUMAN__COORDINATES:
        return getCoordinates();
      case HriDslPackage.HUMAN__SPEED:
        return getSpeed();
      case HriDslPackage.HUMAN__DEXT:
        return getDext();
      case HriDslPackage.HUMAN__FATIGUE_PROFILE:
        return getFatigue_profile();
      case HriDslPackage.HUMAN__FREE_WILL_PROFILE:
        return getFree_will_profile();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HriDslPackage.HUMAN__NAME:
        setName((String)newValue);
        return;
      case HriDslPackage.HUMAN__COORDINATES:
        setCoordinates((Coordinates)newValue);
        return;
      case HriDslPackage.HUMAN__SPEED:
        setSpeed((Float)newValue);
        return;
      case HriDslPackage.HUMAN__DEXT:
        setDext((Integer)newValue);
        return;
      case HriDslPackage.HUMAN__FATIGUE_PROFILE:
        setFatigue_profile((Fatigue_profile)newValue);
        return;
      case HriDslPackage.HUMAN__FREE_WILL_PROFILE:
        setFree_will_profile((Free_will_profile)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HriDslPackage.HUMAN__NAME:
        setName(NAME_EDEFAULT);
        return;
      case HriDslPackage.HUMAN__COORDINATES:
        setCoordinates((Coordinates)null);
        return;
      case HriDslPackage.HUMAN__SPEED:
        setSpeed(SPEED_EDEFAULT);
        return;
      case HriDslPackage.HUMAN__DEXT:
        setDext(DEXT_EDEFAULT);
        return;
      case HriDslPackage.HUMAN__FATIGUE_PROFILE:
        setFatigue_profile(FATIGUE_PROFILE_EDEFAULT);
        return;
      case HriDslPackage.HUMAN__FREE_WILL_PROFILE:
        setFree_will_profile(FREE_WILL_PROFILE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HriDslPackage.HUMAN__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case HriDslPackage.HUMAN__COORDINATES:
        return coordinates != null;
      case HriDslPackage.HUMAN__SPEED:
        return speed != SPEED_EDEFAULT;
      case HriDslPackage.HUMAN__DEXT:
        return dext != DEXT_EDEFAULT;
      case HriDslPackage.HUMAN__FATIGUE_PROFILE:
        return fatigue_profile != FATIGUE_PROFILE_EDEFAULT;
      case HriDslPackage.HUMAN__FREE_WILL_PROFILE:
        return free_will_profile != FREE_WILL_PROFILE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", speed: ");
    result.append(speed);
    result.append(", dext: ");
    result.append(dext);
    result.append(", fatigue_profile: ");
    result.append(fatigue_profile);
    result.append(", free_will_profile: ");
    result.append(free_will_profile);
    result.append(')');
    return result.toString();
  }

} //HumanImpl
