/*
 * generated by Xtext 2.28.0
 */
package it.polimi.hri_designtime.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HriDslUiModule extends AbstractHriDslUiModule {

	public HriDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
