/**
 * generated by Xtext 2.25.0
 */
package it.polimi.hri_designtime.hriDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Behavioral model</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getBehavioral_model()
 * @model
 * @generated
 */
public enum Behavioral_model implements Enumerator
{
  /**
   * The '<em><b>BASE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BASE_VALUE
   * @generated
   * @ordered
   */
  BASE(0, "BASE", "base"),

  /**
   * The '<em><b>ERRORS</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ERRORS_VALUE
   * @generated
   * @ordered
   */
  ERRORS(1, "ERRORS", "err"),

  /**
   * The '<em><b>COG V1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COG_V1_VALUE
   * @generated
   * @ordered
   */
  COG_V1(2, "COG_V1", "cog1"),

  /**
   * The '<em><b>COG V2</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COG_V2_VALUE
   * @generated
   * @ordered
   */
  COG_V2(3, "COG_V2", "cog2");

  /**
   * The '<em><b>BASE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BASE
   * @model literal="base"
   * @generated
   * @ordered
   */
  public static final int BASE_VALUE = 0;

  /**
   * The '<em><b>ERRORS</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ERRORS
   * @model literal="err"
   * @generated
   * @ordered
   */
  public static final int ERRORS_VALUE = 1;

  /**
   * The '<em><b>COG V1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COG_V1
   * @model literal="cog1"
   * @generated
   * @ordered
   */
  public static final int COG_V1_VALUE = 2;

  /**
   * The '<em><b>COG V2</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COG_V2
   * @model literal="cog2"
   * @generated
   * @ordered
   */
  public static final int COG_V2_VALUE = 3;

  /**
   * An array of all the '<em><b>Behavioral model</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Behavioral_model[] VALUES_ARRAY =
    new Behavioral_model[]
    {
      BASE,
      ERRORS,
      COG_V1,
      COG_V2,
    };

  /**
   * A public read-only list of all the '<em><b>Behavioral model</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Behavioral_model> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Behavioral model</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Behavioral_model get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Behavioral_model result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Behavioral model</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Behavioral_model getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Behavioral_model result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Behavioral model</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Behavioral_model get(int value)
  {
    switch (value)
    {
      case BASE_VALUE: return BASE;
      case ERRORS_VALUE: return ERRORS;
      case COG_V1_VALUE: return COG_V1;
      case COG_V2_VALUE: return COG_V2;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Behavioral_model(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Behavioral_model
