/**
 * generated by Xtext 2.25.0
 */
package it.polimi.hri_designtime.hriDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Fatigue profile</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getFatigue_profile()
 * @model
 * @generated
 */
public enum Fatigue_profile implements Enumerator
{
  /**
   * The '<em><b>YOUNG HEALTHY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #YOUNG_HEALTHY_VALUE
   * @generated
   * @ordered
   */
  YOUNG_HEALTHY(0, "YOUNG_HEALTHY", "young_healthy"),

  /**
   * The '<em><b>YOUNG SICK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #YOUNG_SICK_VALUE
   * @generated
   * @ordered
   */
  YOUNG_SICK(1, "YOUNG_SICK", "young_sick"),

  /**
   * The '<em><b>ELDERLY HEALTHY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELDERLY_HEALTHY_VALUE
   * @generated
   * @ordered
   */
  ELDERLY_HEALTHY(2, "ELDERLY_HEALTHY", "elderly_healthy"),

  /**
   * The '<em><b>ELDERLY SICK</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELDERLY_SICK_VALUE
   * @generated
   * @ordered
   */
  ELDERLY_SICK(3, "ELDERLY_SICK", "elderly_sick"),

  /**
   * The '<em><b>COVID PATIENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COVID_PATIENT_VALUE
   * @generated
   * @ordered
   */
  COVID_PATIENT(4, "COVID_PATIENT", "covid_patient");

  /**
   * The '<em><b>YOUNG HEALTHY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #YOUNG_HEALTHY
   * @model literal="young_healthy"
   * @generated
   * @ordered
   */
  public static final int YOUNG_HEALTHY_VALUE = 0;

  /**
   * The '<em><b>YOUNG SICK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #YOUNG_SICK
   * @model literal="young_sick"
   * @generated
   * @ordered
   */
  public static final int YOUNG_SICK_VALUE = 1;

  /**
   * The '<em><b>ELDERLY HEALTHY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELDERLY_HEALTHY
   * @model literal="elderly_healthy"
   * @generated
   * @ordered
   */
  public static final int ELDERLY_HEALTHY_VALUE = 2;

  /**
   * The '<em><b>ELDERLY SICK</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ELDERLY_SICK
   * @model literal="elderly_sick"
   * @generated
   * @ordered
   */
  public static final int ELDERLY_SICK_VALUE = 3;

  /**
   * The '<em><b>COVID PATIENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COVID_PATIENT
   * @model literal="covid_patient"
   * @generated
   * @ordered
   */
  public static final int COVID_PATIENT_VALUE = 4;

  /**
   * An array of all the '<em><b>Fatigue profile</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Fatigue_profile[] VALUES_ARRAY =
    new Fatigue_profile[]
    {
      YOUNG_HEALTHY,
      YOUNG_SICK,
      ELDERLY_HEALTHY,
      ELDERLY_SICK,
      COVID_PATIENT,
    };

  /**
   * A public read-only list of all the '<em><b>Fatigue profile</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Fatigue_profile> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Fatigue profile</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Fatigue_profile get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Fatigue_profile result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Fatigue profile</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Fatigue_profile getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Fatigue_profile result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Fatigue profile</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Fatigue_profile get(int value)
  {
    switch (value)
    {
      case YOUNG_HEALTHY_VALUE: return YOUNG_HEALTHY;
      case YOUNG_SICK_VALUE: return YOUNG_SICK;
      case ELDERLY_HEALTHY_VALUE: return ELDERLY_HEALTHY;
      case ELDERLY_SICK_VALUE: return ELDERLY_SICK;
      case COVID_PATIENT_VALUE: return COVID_PATIENT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Fatigue_profile(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Fatigue_profile
