/**
 * generated by Xtext 2.29.0
 */
package it.polimi.hri_designtime.hriDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Floor</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Floor#getFloor_name <em>Floor name</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Floor#getSurfaces <em>Surfaces</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Floor#getPoints <em>Points</em>}</li>
 * </ul>
 *
 * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getFloor()
 * @model
 * @generated
 */
public interface Floor extends EObject
{
  /**
   * Returns the value of the '<em><b>Floor name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Floor name</em>' attribute.
   * @see #setFloor_name(String)
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getFloor_Floor_name()
   * @model
   * @generated
   */
  String getFloor_name();

  /**
   * Sets the value of the '{@link it.polimi.hri_designtime.hriDsl.Floor#getFloor_name <em>Floor name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Floor name</em>' attribute.
   * @see #getFloor_name()
   * @generated
   */
  void setFloor_name(String value);

  /**
   * Returns the value of the '<em><b>Surfaces</b></em>' containment reference list.
   * The list contents are of type {@link it.polimi.hri_designtime.hriDsl.Surface}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Surfaces</em>' containment reference list.
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getFloor_Surfaces()
   * @model containment="true"
   * @generated
   */
  EList<Surface> getSurfaces();

  /**
   * Returns the value of the '<em><b>Points</b></em>' containment reference list.
   * The list contents are of type {@link it.polimi.hri_designtime.hriDsl.Point}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' containment reference list.
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getFloor_Points()
   * @model containment="true"
   * @generated
   */
  EList<Point> getPoints();

} // Floor
