/**
 * generated by Xtext 2.25.0
 */
package it.polimi.hri_designtime.hriDsl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Free will profile</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getFree_will_profile()
 * @model
 * @generated
 */
public enum Free_will_profile implements Enumerator
{
  /**
   * The '<em><b>NORMAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NORMAL_VALUE
   * @generated
   * @ordered
   */
  NORMAL(0, "NORMAL", "normal"),

  /**
   * The '<em><b>HIGH</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HIGH_VALUE
   * @generated
   * @ordered
   */
  HIGH(1, "HIGH", "high"),

  /**
   * The '<em><b>LOW</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LOW_VALUE
   * @generated
   * @ordered
   */
  LOW(2, "LOW", "low"),

  /**
   * The '<em><b>DISABLED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DISABLED_VALUE
   * @generated
   * @ordered
   */
  DISABLED(3, "DISABLED", "disabled"),

  /**
   * The '<em><b>BUSY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUSY_VALUE
   * @generated
   * @ordered
   */
  BUSY(4, "BUSY", "busy"),

  /**
   * The '<em><b>FREE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FREE_VALUE
   * @generated
   * @ordered
   */
  FREE(5, "FREE", "free"),

  /**
   * The '<em><b>UNEXPERIENCED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNEXPERIENCED_VALUE
   * @generated
   * @ordered
   */
  UNEXPERIENCED(6, "UNEXPERIENCED", "unexperienced"),

  /**
   * The '<em><b>EXPERIENCED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXPERIENCED_VALUE
   * @generated
   * @ordered
   */
  EXPERIENCED(7, "EXPERIENCED", "experienced"),

  /**
   * The '<em><b>CRITICAL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CRITICAL_VALUE
   * @generated
   * @ordered
   */
  CRITICAL(8, "CRITICAL", "critical"),

  /**
   * The '<em><b>STABLE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STABLE_VALUE
   * @generated
   * @ordered
   */
  STABLE(9, "STABLE", "stable"),

  /**
   * The '<em><b>DISTRACTED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DISTRACTED_VALUE
   * @generated
   * @ordered
   */
  DISTRACTED(10, "DISTRACTED", "distracted"),

  /**
   * The '<em><b>FOCUSED</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FOCUSED_VALUE
   * @generated
   * @ordered
   */
  FOCUSED(11, "FOCUSED", "focused");

  /**
   * The '<em><b>NORMAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NORMAL
   * @model literal="normal"
   * @generated
   * @ordered
   */
  public static final int NORMAL_VALUE = 0;

  /**
   * The '<em><b>HIGH</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HIGH
   * @model literal="high"
   * @generated
   * @ordered
   */
  public static final int HIGH_VALUE = 1;

  /**
   * The '<em><b>LOW</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LOW
   * @model literal="low"
   * @generated
   * @ordered
   */
  public static final int LOW_VALUE = 2;

  /**
   * The '<em><b>DISABLED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DISABLED
   * @model literal="disabled"
   * @generated
   * @ordered
   */
  public static final int DISABLED_VALUE = 3;

  /**
   * The '<em><b>BUSY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BUSY
   * @model literal="busy"
   * @generated
   * @ordered
   */
  public static final int BUSY_VALUE = 4;

  /**
   * The '<em><b>FREE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FREE
   * @model literal="free"
   * @generated
   * @ordered
   */
  public static final int FREE_VALUE = 5;

  /**
   * The '<em><b>UNEXPERIENCED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNEXPERIENCED
   * @model literal="unexperienced"
   * @generated
   * @ordered
   */
  public static final int UNEXPERIENCED_VALUE = 6;

  /**
   * The '<em><b>EXPERIENCED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EXPERIENCED
   * @model literal="experienced"
   * @generated
   * @ordered
   */
  public static final int EXPERIENCED_VALUE = 7;

  /**
   * The '<em><b>CRITICAL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CRITICAL
   * @model literal="critical"
   * @generated
   * @ordered
   */
  public static final int CRITICAL_VALUE = 8;

  /**
   * The '<em><b>STABLE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STABLE
   * @model literal="stable"
   * @generated
   * @ordered
   */
  public static final int STABLE_VALUE = 9;

  /**
   * The '<em><b>DISTRACTED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DISTRACTED
   * @model literal="distracted"
   * @generated
   * @ordered
   */
  public static final int DISTRACTED_VALUE = 10;

  /**
   * The '<em><b>FOCUSED</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FOCUSED
   * @model literal="focused"
   * @generated
   * @ordered
   */
  public static final int FOCUSED_VALUE = 11;

  /**
   * An array of all the '<em><b>Free will profile</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Free_will_profile[] VALUES_ARRAY =
    new Free_will_profile[]
    {
      NORMAL,
      HIGH,
      LOW,
      DISABLED,
      BUSY,
      FREE,
      UNEXPERIENCED,
      EXPERIENCED,
      CRITICAL,
      STABLE,
      DISTRACTED,
      FOCUSED,
    };

  /**
   * A public read-only list of all the '<em><b>Free will profile</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Free_will_profile> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Free will profile</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Free_will_profile get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Free_will_profile result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Free will profile</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Free_will_profile getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Free_will_profile result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Free will profile</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Free_will_profile get(int value)
  {
    switch (value)
    {
      case NORMAL_VALUE: return NORMAL;
      case HIGH_VALUE: return HIGH;
      case LOW_VALUE: return LOW;
      case DISABLED_VALUE: return DISABLED;
      case BUSY_VALUE: return BUSY;
      case FREE_VALUE: return FREE;
      case UNEXPERIENCED_VALUE: return UNEXPERIENCED;
      case EXPERIENCED_VALUE: return EXPERIENCED;
      case CRITICAL_VALUE: return CRITICAL;
      case STABLE_VALUE: return STABLE;
      case DISTRACTED_VALUE: return DISTRACTED;
      case FOCUSED_VALUE: return FOCUSED;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Free_will_profile(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Free_will_profile
