/**
 * generated by Xtext 2.25.0
 */
package it.polimi.hri_designtime.hriDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Parameter#getLength_unit <em>Length unit</em>}</li>
 * </ul>
 *
 * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Length unit</b></em>' attribute.
   * The literals are from the enumeration {@link it.polimi.hri_designtime.hriDsl.Length_unit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length unit</em>' attribute.
   * @see it.polimi.hri_designtime.hriDsl.Length_unit
   * @see #setLength_unit(Length_unit)
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getParameter_Length_unit()
   * @model
   * @generated
   */
  Length_unit getLength_unit();

  /**
   * Sets the value of the '{@link it.polimi.hri_designtime.hriDsl.Parameter#getLength_unit <em>Length unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length unit</em>' attribute.
   * @see it.polimi.hri_designtime.hriDsl.Length_unit
   * @see #getLength_unit()
   * @generated
   */
  void setLength_unit(Length_unit value);

} // Parameter
