/**
 * generated by Xtext 2.29.0
 */
package it.polimi.hri_designtime.hriDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Queries</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Queries#getMission <em>Mission</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Queries#getQueries <em>Queries</em>}</li>
 * </ul>
 *
 * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getQueries()
 * @model
 * @generated
 */
public interface Queries extends EObject
{
  /**
   * Returns the value of the '<em><b>Mission</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mission</em>' attribute.
   * @see #setMission(String)
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getQueries_Mission()
   * @model
   * @generated
   */
  String getMission();

  /**
   * Sets the value of the '{@link it.polimi.hri_designtime.hriDsl.Queries#getMission <em>Mission</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mission</em>' attribute.
   * @see #getMission()
   * @generated
   */
  void setMission(String value);

  /**
   * Returns the value of the '<em><b>Queries</b></em>' containment reference list.
   * The list contents are of type {@link it.polimi.hri_designtime.hriDsl.Query}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Queries</em>' containment reference list.
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getQueries_Queries()
   * @model containment="true"
   * @generated
   */
  EList<Query> getQueries();

} // Queries
