/**
 * generated by Xtext 2.25.0
 */
package it.polimi.hri_designtime.hriDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Query</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Query#getQuery_type <em>Query type</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Query#getDuration <em>Duration</em>}</li>
 *   <li>{@link it.polimi.hri_designtime.hriDsl.Query#getRuns <em>Runs</em>}</li>
 * </ul>
 *
 * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getQuery()
 * @model
 * @generated
 */
public interface Query extends EObject
{
  /**
   * Returns the value of the '<em><b>Query type</b></em>' attribute.
   * The literals are from the enumeration {@link it.polimi.hri_designtime.hriDsl.Query_type}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query type</em>' attribute.
   * @see it.polimi.hri_designtime.hriDsl.Query_type
   * @see #setQuery_type(Query_type)
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getQuery_Query_type()
   * @model
   * @generated
   */
  Query_type getQuery_type();

  /**
   * Sets the value of the '{@link it.polimi.hri_designtime.hriDsl.Query#getQuery_type <em>Query type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query type</em>' attribute.
   * @see it.polimi.hri_designtime.hriDsl.Query_type
   * @see #getQuery_type()
   * @generated
   */
  void setQuery_type(Query_type value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getQuery_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link it.polimi.hri_designtime.hriDsl.Query#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

  /**
   * Returns the value of the '<em><b>Runs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Runs</em>' attribute.
   * @see #setRuns(int)
   * @see it.polimi.hri_designtime.hriDsl.HriDslPackage#getQuery_Runs()
   * @model
   * @generated
   */
  int getRuns();

  /**
   * Sets the value of the '{@link it.polimi.hri_designtime.hriDsl.Query#getRuns <em>Runs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Runs</em>' attribute.
   * @see #getRuns()
   * @generated
   */
  void setRuns(int value);

} // Query
