/*
 * generated by Xtext 2.28.0
 */
package it.polimi.hri_designtime.ui.tests;

import com.google.inject.Injector;
import it.polimi.hri_designtime.ui.internal.Hri_designtimeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class HriDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Hri_designtimeActivator.getInstance().getInjector("it.polimi.hri_designtime.HriDsl");
	}

}
